# Generated by Django 2.0.3 on 2018-07-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='join_vip',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
