# Generated by Django 2.0.3 on 2018-07-27 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0004_ticket_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freetipsgame',
            old_name='status',
            new_name='statu',
        ),
    ]
