# Generated by Django 2.0.3 on 2018-07-27 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0005_auto_20180727_0617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freetipsgame',
            old_name='statu',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
    ]
