# Generated by Django 2.0.3 on 2018-07-27 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0006_auto_20180727_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntertipsgame',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tips.Ticket'),
        ),
        migrations.AlterField(
            model_name='rolltipsgame',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tips.Ticket'),
        ),
        migrations.AlterField(
            model_name='viptipsgame',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tips.Ticket'),
        ),
        migrations.DeleteModel(
            name='PunterTicket',
        ),
        migrations.DeleteModel(
            name='RollTicket',
        ),
        migrations.DeleteModel(
            name='VipTicket',
        ),
    ]
