# Generated by Django 2.0.3 on 2018-07-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0008_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='join_vip',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
